---

- name: Ensure configuration directory exists
  file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - '{{ apcupsd__config_directory }}'
    - '{{ apcupsd__logs_directory }}'
    - '{{ apcupsd__lib_directory }}'

- name: Remove default configuration file
  file:
    path: '{{ apcupsd__config_directory }}/apcupsd.conf'
    state: absent
