---
- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags: ['apcupsd']

- name: Install the latest version of apcupsd packages
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - "{{ apcupsd__packages }}"
  tags: ['apcupsd']
