---
- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags: ['apcupsd']

- name: Install the latest version of apcupsd packages
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - "{{ apcupsd__packages }}"
  tags: ['apcupsd']

- name: Install apcupsd file
  template:
    src: apcupsd.conf.j2
    dest: "{{ apcupsd__config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: [ 'restart-apcupsd' ]
  tags: ['apcupsd', 'config']
