---
# tasks file for apcupsd

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Check role availability
  fail:
    msg: 'This module only works on Debian or derivatives like Ubuntu and with Systemd'
  when: ansible_os_family != 'Debian'
    or ansible_service_mgr != 'systemd'
  tags: ['always']

- name: Import init tasks
  import_tasks: init.yml
  tags: ['always']

- name: Import install tasks
  import_tasks: install.yml
  tags: ['apcupsd', 'apcupsd-install']

- name: Import configuration tasks
  import_tasks: configure.yml
  tags: ['apcupsd', 'apcupsd-configure']

- name: Import service tasks
  import_tasks: service.yml
  tags: ['apcupsd', 'apcupsd-service']

- name: Optionally include monitoring tasks
  include_tasks: 'monitoring/{{ apcupsd__monitoring }}.yml'
  when: apcupsd__monitoring is defined
  tags: ['apcupsd', 'apcupsd-monitoring']

- name: Optionally include facts tasks
  include_tasks: facts.yml
  when: apcupsd__facts|bool
  tags: ['apcupsd', 'apcupsd-facts']
