---
# tasks file for apcupsd

- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      skip: true
  tags: ['always']

- name: Check role availability
  fail:
    msg: 'This module only works on Debian or derivatives like Ubuntu'
  when: ansible_os_family != 'Debian'

- import_tasks: install.yml
  tags: ['apcupsd', 'apcupsd-install']

- import_tasks: configure.yml
  tags: ['apcupsd', 'apcupsd-configure']

- import_tasks: service.yml
  tags: ['apcupsd', 'apcupsd-service']
